export type SuccessStory = {
  slug: string;
  title: string;
  category: string;
  destination: string;
  outcome: string;
  date: string;
  summary: string;
  evidence: string;
  evidenceAlt: string;
  video?: string;
  poster?: string;
  featured?: boolean;
};

const evidencePath = (file: string) => `/media/success-stories/evidence/${file}`;

export const successStories: SuccessStory[] = [
  {
    slug: 'norway-client-review',
    title: 'A new work chapter in Norway',
    category: 'Client video review',
    destination: 'Norway',
    outcome: 'Work permit journey supported',
    date: '2026',
    summary: 'A client shares their experience of working with Navigator through a Norway employment pathway.',
    evidence: evidencePath('norway-employment-offer.webp'),
    evidenceAlt: 'Norwegian Directorate of Immigration employment offer document preview',
    video: '/media/success-stories/video/norway-client-review.webm',
    poster: '/media/success-stories/video/norway-client-review-poster.webp',
    featured: true,
  },
  {
    slug: 'australia-national-innovation-858',
    title: 'National Innovation visa granted',
    category: 'Permanent visa',
    destination: 'Australia',
    outcome: 'Subclass 858 granted',
    date: 'August 2026',
    summary: 'A documented National Innovation visa grant, prepared with a focused profile and evidence strategy.',
    evidence: evidencePath('australia-858-national-innovation.webp'),
    evidenceAlt: 'Australian Department of Home Affairs National Innovation visa grant preview',
    featured: true,
  },
  {
    slug: 'australia-491-south-australia',
    title: 'An invitation to South Australia',
    category: 'Skilled migration',
    destination: 'Australia',
    outcome: 'Subclass 491 invitation received',
    date: 'April 2025',
    summary: 'A South Australia state nomination invitation marking the next step toward a skilled migration application.',
    evidence: evidencePath('australia-491-south-australia.webp'),
    evidenceAlt: 'South Australia subclass 491 state nomination invitation preview',
    featured: true,
  },
  {
    slug: 'australia-student-visa',
    title: 'From study plan to Australia',
    category: 'Student visa',
    destination: 'Australia',
    outcome: 'Student visa pathway completed',
    date: 'July 2024',
    summary: 'A student visa case supported from planning and documentation through to the final Australia outcome.',
    evidence: evidencePath('australia-student-visa.webp'),
    evidenceAlt: 'Australian student visa case document preview',
  },
  {
    slug: 'australia-vetassess-motor-mechanic',
    title: 'Skills assessment for a motor mechanic',
    category: 'Skills assessment',
    destination: 'Australia',
    outcome: 'VETASSESS assessment prepared',
    date: 'May 2025',
    summary: 'A trade-profile case prepared around the VETASSESS requirements for Motor Mechanic, ANZSCO 321211.',
    evidence: evidencePath('australia-vetassess-motor-mechanic.webp'),
    evidenceAlt: 'VETASSESS Motor Mechanic skills assessment document preview',
  },
  {
    slug: 'australia-190-priyadarshani',
    title: 'Skilled nomination pathway',
    category: 'Skilled migration',
    destination: 'Australia',
    outcome: 'Subclass 190 outcome documented',
    date: 'May 2025',
    summary: 'A subclass 190 case with a structured nomination and document-preparation journey.',
    evidence: evidencePath('australia-190-priyadarshani.webp'),
    evidenceAlt: 'Australian subclass 190 nomination document preview',
  },
  {
    slug: 'australia-190-sandeep',
    title: 'A clear route to skilled migration',
    category: 'Skilled migration',
    destination: 'Australia',
    outcome: 'Subclass 190 outcome documented',
    date: 'May 2025',
    summary: 'A skilled migration file managed with careful eligibility review and application preparation.',
    evidence: evidencePath('australia-190-sandeep.webp'),
    evidenceAlt: 'Australian subclass 190 nomination document preview',
  },
  {
    slug: 'australia-190-shivansh',
    title: 'Another skilled nomination success',
    category: 'Skilled migration',
    destination: 'Australia',
    outcome: 'Subclass 190 outcome documented',
    date: 'May 2025',
    summary: 'A further subclass 190 case showing the value of a complete, well-organised submission.',
    evidence: evidencePath('australia-190-shivansh.webp'),
    evidenceAlt: 'Australian subclass 190 nomination document preview',
  },
  {
    slug: 'australia-visit-visa',
    title: 'A visit visa prepared with confidence',
    category: 'Visit visa',
    destination: 'Australia',
    outcome: 'Visit visa case supported',
    date: '2025',
    summary: 'A visitor visa file shaped around purpose of travel, supporting documents, and a clear presentation.',
    evidence: evidencePath('australia-visit-visa.webp'),
    evidenceAlt: 'Australian visit visa document preview',
  },
  {
    slug: 'australia-482-february-2026',
    title: 'Skills in Demand for a beauty therapist',
    category: 'Employer-sponsored visa',
    destination: 'Australia',
    outcome: 'Subclass 482 granted',
    date: 'February 2026',
    summary: 'A Skills in Demand visa grant supported through a role-specific employer-sponsored application.',
    evidence: evidencePath('australia-482-feb-2026.webp'),
    evidenceAlt: 'Australian subclass 482 grant notification preview',
  },
  {
    slug: 'australia-482-january-2026',
    title: 'A Skills in Demand visa granted',
    category: 'Employer-sponsored visa',
    destination: 'Australia',
    outcome: 'Subclass 482 granted',
    date: 'January 2026',
    summary: 'A temporary skilled visa case completed with accurate role and supporting-document alignment.',
    evidence: evidencePath('australia-482-jan-2026.webp'),
    evidenceAlt: 'Australian subclass 482 grant notification preview',
  },
  {
    slug: 'australia-482-april-2026-ana',
    title: 'A fresh start through employer sponsorship',
    category: 'Employer-sponsored visa',
    destination: 'Australia',
    outcome: 'Subclass 482 granted',
    date: 'April 2026',
    summary: 'A documented subclass 482 grant for a beauty therapist profile.',
    evidence: evidencePath('australia-482-apr-ana.webp'),
    evidenceAlt: 'Australian subclass 482 grant evidence preview for a beauty therapist profile',
  },
  {
    slug: 'australia-482-april-2026-andre',
    title: 'Another successful sponsored pathway',
    category: 'Employer-sponsored visa',
    destination: 'Australia',
    outcome: 'Subclass 482 granted',
    date: 'April 2026',
    summary: 'A second documented April outcome showing Navigator’s depth across employer-sponsored cases.',
    evidence: evidencePath('australia-482-apr-andre.webp'),
    evidenceAlt: 'Australian subclass 482 grant evidence preview',
  },
  {
    slug: 'australia-482-august-2026-1',
    title: 'Skills in Demand outcome',
    category: 'Employer-sponsored visa',
    destination: 'Australia',
    outcome: 'Subclass 482 granted',
    date: 'August 2026',
    summary: 'A recent Skills in Demand grant added to Navigator’s growing record of employer-sponsored outcomes.',
    evidence: evidencePath('australia-482-aug-2026-1.webp'),
    evidenceAlt: 'Australian subclass 482 grant notification preview',
  },
  {
    slug: 'australia-482-august-2026-2',
    title: 'A second August grant',
    category: 'Employer-sponsored visa',
    destination: 'Australia',
    outcome: 'Subclass 482 granted',
    date: 'August 2026',
    summary: 'Another recent subclass 482 grant, presented with a privacy-conscious evidence preview.',
    evidence: evidencePath('australia-482-aug-2026-2.webp'),
    evidenceAlt: 'Australian subclass 482 grant notification preview',
  },
  {
    slug: 'australia-visa-grant-1',
    title: 'A documented Australia visa grant',
    category: 'Visa outcome',
    destination: 'Australia',
    outcome: 'Visa grant notification received',
    date: '2026',
    summary: 'A visa grant notification shared as part of Navigator’s recent documented case outcomes.',
    evidence: evidencePath('australia-visa-grant-1.webp'),
    evidenceAlt: 'Australian visa grant notification document preview',
  },
  {
    slug: 'australia-visa-grant-2',
    title: 'A second Australia visa outcome',
    category: 'Visa outcome',
    destination: 'Australia',
    outcome: 'Visa grant notification received',
    date: '2026',
    summary: 'Another public-safe grant notification preview from Navigator’s recent client evidence set.',
    evidence: evidencePath('australia-visa-grant-2.webp'),
    evidenceAlt: 'Australian visa grant notification document preview',
  },
  {
    slug: 'czech-work-permit-jaseem',
    title: 'A work permit for the Czech Republic',
    category: 'Europe work permit',
    destination: 'Czech Republic',
    outcome: 'Employment permit issued',
    date: 'August 2026',
    summary: 'A Europe work-permit outcome for a construction and building-maintenance role near Prague.',
    evidence: evidencePath('czech-work-permit-jaseem.webp'),
    evidenceAlt: 'Czech Republic employment permit document preview',
  },
  {
    slug: 'czech-work-permit-santosh',
    title: 'A Czech employment permit approved',
    category: 'Europe work permit',
    destination: 'Czech Republic',
    outcome: 'Employment permit issued',
    date: 'August 2026',
    summary: 'A second Czech employment-permit outcome for a construction and building-maintenance role.',
    evidence: evidencePath('czech-work-permit-santosh.webp'),
    evidenceAlt: 'Czech Republic employment permit document preview',
  },
  {
    slug: 'czech-work-permit-zeeshan',
    title: 'A route into the Czech labour market',
    category: 'Europe work permit',
    destination: 'Czech Republic',
    outcome: 'Employment permit issued',
    date: 'August 2026',
    summary: 'A further work-permit case prepared around employer, role, and permit requirements.',
    evidence: evidencePath('czech-work-permit-zeeshan.webp'),
    evidenceAlt: 'Czech Republic employment permit document preview',
  },
  {
    slug: 'czech-work-permit-gajendran',
    title: 'A documented Europe work outcome',
    category: 'Europe work permit',
    destination: 'Czech Republic',
    outcome: 'Employment permit issued',
    date: 'August 2026',
    summary: 'A fourth Czech work-permit outcome from the same successful employer-linked pathway.',
    evidence: evidencePath('czech-work-permit-gajendran.webp'),
    evidenceAlt: 'Czech Republic employment permit document preview',
  },
];

export const featuredSuccessStories = successStories.filter((story) => story.featured);

export const getSuccessStory = (slug: string) => successStories.find((story) => story.slug === slug);
